services:
  db:
    image: postgres:17.5-alpine
    container_name: db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: sport-db
    ports:
      - "5433:5432"
    volumes:
      - ./init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
#      - pgdata:/var/lib/postgresql/data
    networks:
      - webflux-etl-process


#volumes:
#  pgdata:

networks:
  webflux-etl-process:
    driver: bridge
