server:
  port: 8080

spring:
  application:
    name: webflux-etl-process
  main:
    web-application-type: reactive
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/sport-db
    username: test
    password: test
  datasource:
    initialization-mode: always
  sql:
    init:
      mode: always
  data:
    r2dbc:
      repositories:
        enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

rakuten:
  app-id: 1088439895795118344
  affiliate-id: 4888e03c.650fca1f.4888e03d.0d5cfe5c
  app-secret: 50ed365c9e413f318503dbf9e6ee263a896b760d
  callback-domain: webservice.rakuten.co.jp
  api-host: app.rakuten.co.jp
  api-path: /services/api/IchibaItem/Search/20170706

logging:
  level:
    root: info
    io.r2dbc.postgresql: debug
    com.epam.springboot.advanced: debug
